# Generated by Django 4.1.4 on 2023-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
