# Generated by Django 4.1.4 on 2023-01-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0002_shirts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shirts_images'),
        ),
    ]
