# Generated by Django 4.1.4 on 2023-01-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0003_shirts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='image',
            field=models.ImageField(blank=True, default='\\coachs_images\\silueta_camiseta.jpg', null=True, upload_to='shirts_images', verbose_name='shirt_image'),
        ),
    ]
