# Generated by Django 4.1.4 on 2023-01-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('position', models.CharField(choices=[('arquero', 'arquero'), ('defensor', 'defensor'), ('volante', 'volante'), ('delantero', 'delantero')], max_length=50)),
            ],
        ),
    ]
