# Generated by Django 4.1.4 on 2023-01-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_players_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='image',
            field=models.ImageField(blank=True, default='\\players_images\\silueta.jpg', null=True, upload_to='players_images', verbose_name='imagen'),
        ),
    ]
